<?php
session_start();
ob_start("ob_gzhandler");
set_time_limit(0);
error_reporting(0);
include("inc/include.php");
oturum_koru();
define("idokey", "1", true);

/** Error reporting */
error_reporting(0);
ini_set('display_errors', false);
ini_set('display_startup_errors', false);
date_default_timezone_set('Europe/Istanbul');
if (PHP_SAPI == 'cli')
    die('This example should only be run from a Web Browser');
/** Include PHPExcel */
require_once dirname(__FILE__) . '/inc/PHPExcel.php';

function exportExcel($filename='ExportExcel',$columns=array(),$data=array(),$replaceDotCol=array()){

    // Create new PHPExcel object
    $objPHPExcel = new PHPExcel();
    // Set document properties
    $objPHPExcel->getProperties()->setCreator("GoInteraktif Panel")
        ->setLastModifiedBy("Go Interaktif Panel")
        ->setTitle("Office 2007 XLSX GoInteraktif Panel Kargo Export")
        ->setSubject("Office 2007 XLSX GoInteraktif Panel Kargo Export")
        ->setDescription("GoInteraktif Panel Kargo Export Office 2007 XLSX, generated by GoInteraktif Panel using PHP.")
        ->setKeywords("GoInteraktif Panel Kargo Export")
        ->setCategory("GoInteraktif Panel Kargo Export");

    // Redirect output to a client’s web browser (Excel5)
    header('Content-Type: application/vnd.ms-excel');
    header('Content-Disposition: attachment;filename="'.$filename.'.xls"');
    header('Cache-Control: max-age=0');
    // If you're serving to IE 9, then the following may be needed
    header('Cache-Control: max-age=1');
    // If you're serving to IE over SSL, then the following may be needed
    header ('Expires: Mon, 26 Jul 1997 05:00:00 GMT'); // Date in the past
    header ('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT'); // always modified
    header ('Cache-Control: cache, must-revalidate'); // HTTP/1.1
    header ('Pragma: public'); // HTTP/1.0

    $say=count($columns);

    $alphas = range('A', 'Z');

    foreach($columns AS $index => $value){

        // Add some data
        $objPHPExcel->setActiveSheetIndex(0)->setCellValue($alphas[$index]."1", $value);

        foreach($data AS $i => $d){

            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($alphas[$index].($i+2), $d[$index]);

        }

    }

    // Rename worksheet
    $objPHPExcel->getActiveSheet()->setTitle($filename);

    // Set active sheet index to the first sheet, so Excel opens this as the first sheet
    $objPHPExcel->setActiveSheetIndex(0);

    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
    $objWriter->save('php://output');

    exit;
}

if (!$_SESSION["user_type"] == 1) {
    exit();
}

$dizim = array();

$durums = explode(",", $_GET["durumlar"]);

$tipler = mysql_real_escape_string(strip_tags($_GET["tipler"]));
$durumlar = mysql_real_escape_string(strip_tags($_GET["durumlar"]));


if (empty($_GET["tipler"])) {
    exit("tipler Boş Alamaz");
}
if (empty($_GET["durumlar"])) {
    exit("Durumlar Boş Alamaz");
}


$ip = $_SERVER['REMOTE_ADDR'];



/* TANIMLAMALAR */

$columns = array();

$data = array();


$replaceDotCol = array(3);


/* Sütun Başlıkları */
$columns = array(
    'info',
    'number'
);


/*$going = $db->get_results("SELECT name_surname,phone FROM  customer where customer_id in(".$cSd.") ");
    foreach ($going as  $value) {
        echo $value->name_surname." - ".$value->phone."<br>";
    }*/


//$tipler,$durumlar;

$api_filter = null;

if(strlen($_GET["apis"])>=1){
    $api_filter = " AND  private_api IN(".$_GET["apis"].")";
}

$d = $db->get_results("SELECT ad_soyad,Telefon_no,update_date,siparis_durumu,kayit_tarihi,islem_tarihi FROM  siparisler WHERE siparis_tipi IN(" . $tipler . ") AND  siparis_durumu IN(" . $durumlar . ")".$api_filter);
if ($d) {
    $bTarih = strtotime(base64_decode(str_replace("==", null, $_GET["bTarih"])));
    $sTarih = strtotime(base64_decode(str_replace("==", null, $_GET["sTarih"])));
    $dump = array();
    foreach ($d as $value) {
        /* Satır Verileri */
        if($value->siparis_durumu==3){
            if(
                (strtotime($value->islem_tarihi)<$bTarih)
                ||(strtotime($value->islem_tarihi)>$sTarih)
            ){
                continue;
            }
        }else{
            if(
                (strtotime($value->kayit_tarihi)<$bTarih)
                ||(strtotime($value->kayit_tarihi)>$sTarih)
            ){
                continue;
            }
        }
        $TelNo = null;
        if(substr(substr($value->Telefon_no, -10), 0, 1)==0){
            continue;
        }
        $data[] = array(
            $value->ad_soyad,
            substr($value->Telefon_no, -10)

        );
    }
}

$DosyaAdi = date("Y-m-d") . "- Data Aktarım";

exportExcel($DosyaAdi, $columns, $data, $replaceDotCol);

exit;

?>